default[:deploy_keys][:user] = "rails-app"
default[:deploy_keys][:box_name] = "vagrant"
default[:deploy_keys][:github_user] = "your_user"
default[:deploy_keys][:github_token] = "token"
default[:deploy_keys][:github_repo] = "my_repo"